# Generated by Django 4.1.1 on 2022-10-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentar',
        ),
    ]
